### ISSUE TITLE
bug(tools): experiment_only_ingest_path and experiment_run_grafana_demo pass stale prometheus_url= to controller_service.start()

### ISSUE THREAD

**Issue by milindsrivastava1997** [ProjectASAP/ASAPQuery#445]
## Bug

`experiment_only_ingest_path.py` and `experiment_run_grafana_demo.py` both call `controller_service.start()` with a stale `prometheus_url=prometheus_url` keyword argument and are **missing the required `discovery_backend` parameter**.

PR #396 refactored `misc.py`'s `ControllerService.start()` to replace `prometheus_url: Optional[str]` with `discovery_backend: DiscoveryBackend` (a required parameter with no default). It updated `experiment_run_clickhouse.py` and `experiment_run_e2e.py`, but left these two scripts behind.

## Effect

- `prometheus_url=prometheus_url` silently disappears into `**kwargs` — the Prometheus URL is never used.
- `discovery_backend` is missing entirely → **`TypeError: start() missing 1 required positional argument: 'discovery_backend'`** at runtime.

## Broken call sites

**`experiment_only_ingest_path.py`** (~line 298):
```python
controller_service.start(
    controller_input_file=controller_input_config,
    streaming_engine=args.streaming_engine,
    controller_remote_output_dir=CONTROLLER_REMOTE_OUTPUT_DIR,
    punting=args.controller_punting,
    prometheus_url=prometheus_url,   # stale kwarg, silently dropped
    # discovery_backend=...          # required, missing
)
```

**`experiment_run_grafana_demo.py`** (~line 351):
```python
controller_service.start(
    controller_input_file=controller_input_config,
    streaming_engine=args.streaming_engine,
    controller_remote_output_dir=CONTROLLER_REMOTE_OUTPUT_DIR,
    punting=args.controller_punting,
    prometheus_url=prometheus_url,   # stale kwarg, silently dropped
    # discovery_backend=...          # required, missing
)
```

## Fix

Replace `prometheus_url=prometheus_url` with:
```python
discovery_backend=DiscoveryBackend(
    type="prometheus",
    url=prometheus_url,
    database=None,
),
```

Matching the pattern already used in `experiment_run_e2e.py`.

## Root cause

Introduced in #396 — `misc.py` was updated but these two scripts were not.
